### ISSUE TITLE
is this supported for latest version 

### ISSUE THREAD

**Issue by dsgolfside** [telabotanica/bp-moderate-group-creation#15]
first to the genius who created this much needed feature ..... is this ok to use on latest wordpress and buddypress ?    have you reached out to buddypress developers to get them to add this feature ?

here's the situation .....groups vital to community perhaps most vital ..... allowing members to create gives them a stake in the community = huge value .....problem spammers and just others create groups neither myself or other site owners want included in site

**Comment by matcho** [comment]
Hi. Thanks for the positive feedback.
Currently works (tested) with WP 5.1.1 and BP… not sure… @kstefanini ?

Did not get in touch with WP developers at the moment, good idea.

**Comment by dsgolfside** [comment]
Let’s all talk to Boone and John James the creators of buddypress lobby for including in core ...moderate just like comments the already have an entire groups section in admin

**Comment by kstefanini** [comment]
Yes it works with latest versions!

> Currently works (tested) with WP 5.1.1 and BP

And BuddyPress 4.2.0
